service: lxp-chime

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  timeout: 900
  memorySize: 3008

  # # Accept stage from command line, defaults to dev
  # # - Should be EITHER prod or dev
  # stage: ${opt:stage, 'dev'}

functions:
  server:
    handler: dist/server/handler.server
    events:
      - http: ANY /
      - http: "ANY {proxy+}"
      - cors: true

# Add in custom section to define appsync here

resources:
  Resources:
    Meetings:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "Title"
            AttributeType: "S"
          - AttributeName: "Passcode"
            AttributeType: "S"
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: "Title"
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: "Passcode"
            KeySchema:
              - AttributeName: "Passcode"
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        TimeToLiveSpecification:
          AttributeName: "TTL"
          Enabled: true
    Attendees:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "AttendeeId"
            AttributeType: "S"
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: "AttendeeId"
            KeyType: HASH

package:
  include:
    - dist/**
    - package.json
    - node_modules/**
  exclude:
    - ./**
